#!/usr/bin/env python3

import os
import sys
from datetime import datetime

# Import fetch_problem_statement from generate_data
from generate_data import fetch_problem_statement

# Fetch environment variables
issue_id = os.environ.get('ISSUE_ID')
repository = os.environ.get('REPOSITORY')
organization = os.environ.get('ORGANIZATION')
github_token = os.environ.get('GH_TOKEN')
fail_to_pass = os.environ.get('FAIL_TO_PASS', '')
pass_to_pass = os.environ.get('PASS_TO_PASS', '')

# Validate required environment variables
if not all([issue_id, repository, organization, github_token]):
    print("Error: Missing required environment variables", file=sys.stderr)
    sys.exit(1)

# Fetch issue details using fetch_problem_statement function
try:
    # Get issue title and body using fetch_problem_statement
    issue_data = fetch_problem_statement(organization, repository, issue_id)
    
    # Extract title and body from the returned dictionary
    issue_title = issue_data.get('title', '')
    issue_body = issue_data.get('body', '')

    # Create the commit message from template
    commit_message = f"""{issue_title} #{issue_id}

{issue_body}

FAIL_TO_PASS: {fail_to_pass}
PASS_TO_PASS: {pass_to_pass}

Generated by GitHub Action on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"""

    # Output the commit message
    print(commit_message)

except Exception as e:
    print(f"Error fetching issue details: {str(e)}", file=sys.stderr)
    sys.exit(1)
