name: Generate dataset data for issue
run-name: "[${{ github.event.inputs.organization }}/${{ github.event.inputs.repository }}][${{ github.event.inputs.generator }}] Update Data for issue #${{ github.event.inputs.issue_id }}"

on:
  workflow_dispatch:
    inputs:
      generator:
        description: 'Profile'
        required: true
        default: 'java'
        type: choice
        options:
          - java
      organization:
        description: 'GitHub organization name'
        required: true
        default: 'dpai-benchmark'
        type: string
      repository:
        description: 'Repository name (repo)'
        required: true
        type: string
      issue_id:
        description: 'Issue number'
        required: true
        type: string
      auto_merge:
        description: 'Automatically merge data updates'
        required: false
        type: boolean
        default: false

jobs:
  update-data:
    runs-on: ubuntu-latest
    outputs:
      gist_url: ${{ steps.update-data.outputs.gist_url }}
      has_error: ${{ steps.update-data.outputs.has_error }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Update Data
        id: update-data
        uses: ./.github/actions/update-issue-data
        with:
          generator: ${{ github.event.inputs.generator }}
          organization: ${{ github.event.inputs.organization }}
          repository: ${{ github.event.inputs.repository }}
          issue_id: ${{ github.event.inputs.issue_id }}
          github_token: ${{ secrets.PROJECT_TOKEN }}
          dataset_repo: ${{ vars.DATASET_REPO }}
          auto_merge: ${{ github.event.inputs.auto_merge }}
          update_status: 'true'