name: Update Issue SWE Data
run-name: "[${{ github.event.inputs.organization }}/${{ github.event.inputs.repository }}][${{ github.event.inputs.generator }}] Update SWE Data for issue #${{ github.event.inputs.issue_id }}"

on:
  workflow_dispatch:
    inputs:
      generator:
        description: 'Profile'
        required: true
        default: 'java'
        type: choice
        options:
          - java
      organization:
        description: 'GitHub organization name'
        required: true
        default: 'jetbrains-eval-lab'
        type: string
      repository:
        description: 'Repository name (repo)'
        required: true
        type: string
      issue_id:
        description: 'Issue number'
        required: true
        type: string

jobs:
  update-swe-data:
    runs-on: ubuntu-latest
    outputs:
      gist_url: ${{ steps.update-swe-data.outputs.gist_url }}
      has_error: ${{ steps.update-swe-data.outputs.has_error }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Update SWE Data
        id: update-swe-data
        uses: ./.github/actions/update-issue-swe-data
        with:
          generator: ${{ github.event.inputs.generator }}
          organization: ${{ github.event.inputs.organization }}
          repository: ${{ github.event.inputs.repository }}
          issue_id: ${{ github.event.inputs.issue_id }}
          github_token: ${{ secrets.PROJECT_TOKEN }}
          dataset_repo: ${{ env.DATASET_REPO }}
          update_status: 'true'